### ISSUE TITLE
Downloading more than 50 actions

### ISSUE THREAD

**Issue by DagothRa** [CuriousNekomimi/AIDCAT#5]
I ran this almost two weeks ago to export my stories, including one with over 15,000 actions (yes, I know). Everything was exported including that full story, resulting in a 3.88 MB file.

Since you now have support for importing into KoboldAI, I figured I'd get the latest version of this tool and re-run it to download my AI Dungeon stories. This results in a much smaller file, only 293 KB. I checked and found that it now seems to cap out at the 50 most recent actions of the story.

I still have the older version of this tool, so I ran it again to see if the change was on your end or AI Dungeon, and it downloaded the full 3.88 MB file again. So that tells me it's a change made to this tool.

I'm guessing it's to keep things from getting to bloated before importing into KoboldAI or something, only keeping a certain number of relevant actions which would be potentially referenced by it? Is there an option somewhere now to download the full adventures again, or at least can you provide clarification on the reason for this?

**Comment by CuriousNekomimi** [comment]
I have reverted some of the changes I made yesterday. I had changed `actions` to `actionWindow` in the adventure query. Reverting to `actions` should solve the issue and result in a complete download. I have uploaded a fix as v0.6.5. Thank you for the report! Please try the new upload and let me know if the issue has been resolved.

**Comment by DagothRa** [comment]
I can confirm it is now downloading everything again. The file size actually grew to 10.8 MB with the nicer formatting instead of being in compressed format, though that's fine. Much easier to manually view this way.

**Comment by CuriousNekomimi** [comment]
Excellent, Thank you!
