### ISSUE TITLE
Saving bookmarked scenarios fails if any sub-scenario fetch returns None.

### ISSUE THREAD

**Issue by Alephrin** [CuriousNekomimi/AIDCAT#6]
For reasons unknown to me, certain sub-scenarios in my bookmarks return {Scenario: None}. This satisfies the if 'scenario' in result['data'] check but causes an exception when the script tries to progress and halts.

I was able to do a quick fix locally by changing
```if 'data' in result and 'scenario' in result['data']:```
to
```if 'data' in result and 'scenario' in result['data'] and result['data']['scenario'] != None:```

**Comment by CuriousNekomimi** [comment]
Thank you. A fix has been pushed.
