### ISSUE TITLE
Tools to help migrate from AID to KAI

### ISSUE THREAD

**Issue by thaalesalves** [CuriousNekomimi/AIDCAT#9]
I created some simple tools to help integrate AIDCAT and KAI so people could migrate from AID faster. The scripts I made interpret AIDCAT's output in a "scenario explorer" that lets the person select their scenario, type the placeholders just like in AID and then save the generated story into a file ready to be used in KoboldAI. Same for my own scenarios (it has its own script) and another tool that converts AIDCAT's extracted stories from AID into something readable by KoboldAI.

I plan to join these three tools into one, but for now they're separated. This might be useful for people using AIDCAT.
Here's the link: https://github.com/thaalesalves/aid-scripts/tree/main/other

**Comment by CuriousNekomimi** [comment]
I believe KoboldAI already supports this.
